version: '3.1'
services:
  odoo:
    user: root
    image: odoo:14.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    command: sleep infinity
    volumes:
      - ./odoo_addons:/usr/lib/python3/dist-packages/odoo/extra-addons:cached
      - ./config:/usr/lib/python3/dist-packages/odoo/odoo
      - ./.vscode:/usr/lib/python3/dist-packages/odoo/.vscode
  db:
    image: postgres:13
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql:/var/lib/postgresql/data
  pgadmin4:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin@2022
    ports:
      - "5050:5050"
    depends_on:
      - db
    